name: openfe_analysis_env
channels:
  - conda-forge
dependencies:
  - click
  - MDAnalysis
  - netCDF4
  - openff-units
  - pip
  - tqdm
  - pyyaml
  # for testing
  - coverage
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-rerunfailures
  - pip:
    - git+https://github.com/fatiando/pooch@main  # related to https://github.com/fatiando/pooch/issues/502
